### ISSUE TITLE
Adaptor or Adapter? ;)

### ISSUE THREAD

**Issue by caspervonb** [Microsoft/edge-diagnostics-launch#2]
Trivial issue, the edge adapter is called.. well edge diagnostics _adaptor_. Where'as this module refers to it as the adapter.

**Comment by caspervonb** [comment]
Ah the npm package ships it as adapter, outdated documentation (executable name) in the edge-diagnostics-adaptor repository.

**Comment by auchenberg** [comment]
We should use `adapter` consistently. https://github.com/Microsoft/edge-diagnostics-adapter/issues/22
